component_depth: 1
languages: 
- java 
exclude:
- ./api/.*
- ./bin/.*
- ./bin/org/.*
- ./bin/org/apache/.*
- ./bin/org/apache/log4j/.*
- ./bin/org/apache/log4j/config/.*
- ./bin/org/apache/log4j/helpers/.*
- ./bin/org/apache/log4j/spi/.*
- ./bin/org/apache/log4j/util/.*
- ./bin/org/apache/log4j/xml/.*
- ./bin/org/apache/logging/.*
- ./bin/org/apache/logging/dumbster/.*
- ./bin/org/apache/logging/dumbster/smtp/.*
- ./bin/org/apache/logging/log4j/.*
- ./bin/org/apache/logging/log4j/core/.*
- ./bin/org/apache/logging/log4j/core/appender/.*
- ./bin/org/apache/logging/log4j/core/appender/rewrite/.*
- ./bin/org/apache/logging/log4j/core/appender/rolling/.*
- ./bin/org/apache/logging/log4j/core/appender/rolling/helper/.*
- ./bin/org/apache/logging/log4j/core/appender/routing/.*
- ./bin/org/apache/logging/log4j/core/config/.*
- ./bin/org/apache/logging/log4j/core/config/plugins/.*
- ./bin/org/apache/logging/log4j/core/filter/.*
- ./bin/org/apache/logging/log4j/core/helpers/.*
- ./bin/org/apache/logging/log4j/core/impl/.*
- ./bin/org/apache/logging/log4j/core/jmx/.*
- ./bin/org/apache/logging/log4j/core/layout/.*
- ./bin/org/apache/logging/log4j/core/lookup/.*
- ./bin/org/apache/logging/log4j/core/net/.*
- ./bin/org/apache/logging/log4j/core/pattern/.*
- ./bin/org/apache/logging/log4j/core/selector/.*
- ./bin/org/apache/logging/log4j/core/util/.*
- ./bin/org/apache/logging/log4j/core/web/.*
- ./bin/org/apache/logging/log4j/flume/.*
- ./bin/org/apache/logging/log4j/flume/appender/.*
- ./bin/org/apache/logging/log4j/jcl/.*
- ./bin/org/apache/logging/log4j/message/.*
- ./bin/org/apache/logging/log4j/samples/.*
- ./bin/org/apache/logging/log4j/samples/app/.*
- ./bin/org/apache/logging/log4j/samples/dto/.*
- ./bin/org/apache/logging/log4j/samples/events/.*
- ./bin/org/apache/logging/log4j/samples/util/.*
- ./bin/org/apache/logging/log4j/simple/.*
- ./bin/org/apache/logging/log4j/spi/.*
- ./bin/org/apache/logging/log4j/status/.*
- ./bin/org/apache/logging/log4j/test/.*
- ./bin/org/apache/logging/log4j/test/appender/.*
- ./bin/org/apache/logging/log4j/util/.*
- ./bin/org/apache/logging/slf4j/.*
- ./core/.*
- ./dist/.*
- ./flume-ng/.*
- ./jcl-bridge/.*
- ./lib/.*
- ./log4j-to-slf4j/.*
- ./log4j12-api/.*
- ./samples/.*
- ./samples/flume-common/.*
- ./samples/flume-embedded/.*
- ./samples/flume-remote/.*
- ./slf4j-impl/.*
- ./web/.*
